-- ============================================================================
-- LANZ.SYS portfolio — starting content (generated by scripts/build-seed.mjs)
-- Run AFTER schema.sql. Each table is only filled if it is still empty,
-- so running this again never duplicates or overwrites your edits.
-- ============================================================================

insert into public.profile (id, name, roles, role, tagline, intro, about, image, image_alt, player_class, specialization, availability, location, email, career_goal)
values (1, 'JAYZEL LANCE MACATUGGAL', array['Virtual Assistant', 'Creative Digital Professional', 'Computer Science Student']::text[], 'VIRTUAL ASSISTANT / CREATIVE DIGITAL PROFESSIONAL', 'Digital experiences, creative solutions, organized workflows.', 'Computer Science student building digital experiences, creative solutions, and organized workflows.', 'I bring software thinking and creative execution together: shaping an idea, organizing its moving parts, and building a clear experience around it.', '/assets/profile-placeholder.svg', 'Abstract profile placeholder; replace with a portrait when ready', 'Computer Science Student', 'Software development + creative digital work', 'Open to selected opportunities', 'Philippines', 'example@email.com', 'Add career goal')
on conflict (id) do nothing;

insert into public.resume (id, title, description, file, url, status)
values (1, 'Resume / CV', 'A concise overview of education, skills, and selected work.', null, null, 'Resume placeholder')
on conflict (id) do nothing;

insert into public.skills (name, category, level, description, related, sort_order)
select * from (values
  ('React', 'Technical', 'Intermediate', 'Component-driven interfaces and responsive web experiences.', array['JavaScript', 'CSS']::text[], 0),
  ('JavaScript', 'Technical', 'Intermediate', 'Interactive frontend applications and browser APIs.', array['React', 'Vite']::text[], 1),
  ('Python', 'Technical', 'Intermediate', 'Scripting, automation, APIs, and experimentation.', array['AI / ML', 'GIS']::text[], 2),
  ('GIS', 'Technical', 'Intermediate', 'Interactive maps and location-based application concepts.', array['Leaflet', 'FloodWatch GIS']::text[], 3),
  ('AI / ML', 'Technical', 'Beginner', 'Computer vision and machine-learning experimentation.', array['Python', 'YOLO']::text[], 4),
  ('UI / UX', 'Creative', 'Intermediate', 'Visual hierarchy, interface structure, and practical user flows.', array['Figma', 'Web']::text[], 5),
  ('Video Editing', 'Creative', 'Intermediate', 'Short-form edits, presentations, and digital content.', array['Motion', 'Audio']::text[], 6),
  ('Virtual Assistance', 'Digital', 'Intermediate', 'Organized digital support, research, and admin workflows.', array['Research', 'Documentation']::text[], 7),
  ('Research', 'Digital', null, 'Add a short description of research and information-gathering workflows.', array['Documentation']::text[], 8),
  ('Data Management', 'Administrative', null, 'Add details about data organization and record-keeping workflows.', array['Spreadsheets']::text[], 9),
  ('Social Media', 'Social', null, 'Add details about content and social-platform workflows.', array['Content planning']::text[], 10)
) as v(name, category, level, description, related, sort_order)
where not exists (select 1 from public.skills);

insert into public.services (name, category, description, capabilities, deliverables, tools, availability, related_projects, cta, featured, sort_order)
select * from (values
  ('Video Editing', null, 'Shape raw footage into a clear, paced visual story for digital channels.', array['Assembly and pacing', 'Titles and transitions', 'Export preparation']::text[], array['Edited video', 'Exported formats']::text[], array['Adobe Premiere Pro', 'After Effects', 'CapCut']::text[], null, '{}'::text[], 'Discuss video editing', false, 0),
  ('Website Design', null, 'Plan and build responsive websites with clear structure and a considered visual system.', array['Page structure', 'Responsive UI', 'Component planning']::text[], array['Responsive interface', 'Reusable components']::text[], array['React', 'Vite', 'CSS', 'Figma']::text[], null, array['Project Example']::text[], 'Discuss a website', false, 1),
  ('Social Media Management', null, 'Support consistent social publishing with organized content and platform workflows.', array['Content scheduling', 'Publishing support', 'Asset organization']::text[], array['Content calendar placeholder', 'Organized assets']::text[], array['Meta Business Suite', 'Canva']::text[], null, '{}'::text[], 'Discuss social media support', false, 2),
  ('Graphic Design', null, 'Create clear digital graphics for content, presentations, and online use.', array['Layout', 'Typography', 'Visual assets']::text[], array['Digital graphics', 'Exported assets']::text[], array['Photoshop', 'Canva', 'Figma']::text[], null, '{}'::text[], 'Discuss graphic design', false, 3),
  ('Content Creation', null, 'Organize ideas and materials into practical, ready-to-publish digital content.', array['Content preparation', 'Visual coordination', 'Publishing handoff']::text[], array['Content assets', 'Publishing-ready files']::text[], array['Canva', 'CapCut', 'Notion']::text[], null, '{}'::text[], 'Discuss content creation', false, 4),
  ('Data Entry / Data Management', null, 'Structure and maintain information in clear, consistent digital records.', array['Data entry', 'Formatting', 'Record organization']::text[], array['Organized records', 'Formatted spreadsheets']::text[], array['Google Workspace', 'Microsoft Office']::text[], null, '{}'::text[], 'Discuss data support', false, 5),
  ('Research', null, 'Gather and organize information into concise, useful working notes.', array['Information gathering', 'Source organization', 'Summary preparation']::text[], array['Research notes', 'Source list']::text[], array['Google Workspace', 'Notion']::text[], null, '{}'::text[], 'Discuss research', false, 6),
  ('General Virtual Assistance', null, 'Provide organized day-to-day digital support across administrative and online tasks.', array['Task coordination', 'Document organization', 'Online support']::text[], array['Organized documents', 'Task notes']::text[], array['Google Workspace', 'Microsoft Office', 'Notion']::text[], null, '{}'::text[], 'Discuss virtual assistance', false, 7)
) as v(name, category, description, capabilities, deliverables, tools, availability, related_projects, cta, featured, sort_order)
where not exists (select 1 from public.services);

insert into public.tools (name, category, usage, proficiency, sort_order)
select * from (values
  ('Adobe Premiere Pro', 'Creative', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 0),
  ('After Effects', 'Creative', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 1),
  ('Photoshop', 'Creative', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 2),
  ('Canva', 'Creative', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 3),
  ('Figma', 'Design', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 4),
  ('WordPress', 'Web', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 5),
  ('Google Workspace', 'Productivity', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 6),
  ('Microsoft Office', 'Productivity', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 7),
  ('Notion', 'Organization', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 8),
  ('CapCut', 'Creative', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 9),
  ('Meta Business Suite', 'Social', 'Add a short description of how you use this tool.', 'Add qualitative proficiency', 10)
) as v(name, category, usage, proficiency, sort_order)
where not exists (select 1 from public.tools);

insert into public.projects (name, category, status, year, description, objective, challenge, solution, role, features, results, tech, cover_image, video, gallery, github_url, live_url, featured, sort_order)
select * from (values
  ('FloodWatch GIS', 'AI / GIS', 'Ongoing', '2026', 'An AI-powered real-time flood monitoring concept focused on visualizing current flood conditions and CCTV-derived information.', 'Visualize current flood conditions and CCTV-derived information.', 'Add verified challenge details.', 'Add verified solution details.', 'Add role details', array['Real-time flood monitoring concept', 'Visualization of current flood conditions', 'CCTV-derived information']::text[], '{}'::text[], array['React', 'Leaflet', 'Python', 'YOLO']::text[], null, null, '[]'::jsonb, null, null, true, 0),
  ('Project Example', 'Web / Mobile', 'Planned', '2025', 'Add project description. Replace this mock entry with a project overview and the problem it addresses.', 'Add project objective.', 'Add project challenge.', 'Add project solution.', 'Add role details', array['Add project feature']::text[], '{}'::text[], array['React', 'Add technology']::text[], null, null, '[]'::jsonb, null, null, false, 1),
  ('Project Example', 'Web Development', 'In Progress', '2026', 'Add project description. Use this entry for a software, creative, or digital services project.', 'Add project objective.', 'Add project challenge.', 'Add project solution.', 'Add role details', array['Add project feature']::text[], '{}'::text[], array['Add technology']::text[], null, null, '[]'::jsonb, null, null, false, 2)
) as v(name, category, status, year, description, objective, challenge, solution, role, features, results, tech, cover_image, video, gallery, github_url, live_url, featured, sort_order)
where not exists (select 1 from public.projects);

insert into public.experience (title, organization, period, description, sort_order)
select * from (values
  ('Experience Placeholder', 'Add organization or context', 'Add dates', 'Add a concise description of your responsibilities and work.', 0)
) as v(title, organization, period, description, sort_order)
where not exists (select 1 from public.experience);

insert into public.education (title, organization, period, description, sort_order)
select * from (values
  ('Education Placeholder', 'Add school or institution', 'Add dates', 'Add your program, focus areas, and relevant details.', 0)
) as v(title, organization, period, description, sort_order)
where not exists (select 1 from public.education);

insert into public.certificates (title, issuer, issued_on, credential_id, credential_url, description, image, file, related_skills, sort_order)
select * from (values
  ('Certificate Placeholder', 'Add issuing organization', null::date, 'Add credential ID', null, 'Add certificate description', null, null, '{}'::text[], 0),
  ('Certificate Placeholder', 'Add issuing organization', null::date, 'Add credential ID', null, 'Add certificate description', null, null, '{}'::text[], 1),
  ('Certificate Placeholder', 'Add issuing organization', null::date, 'Add credential ID', null, 'Add certificate description', null, null, '{}'::text[], 2)
) as v(title, issuer, issued_on, credential_id, credential_url, description, image, file, related_skills, sort_order)
where not exists (select 1 from public.certificates);

insert into public.social_links (platform, label, url, sort_order)
select * from (values
  ('facebook', 'Facebook', 'https://www.facebook.com/MaCatzz', 0),
  ('instagram', 'Instagram', 'https://www.instagram.com/lanzzonness', 1),
  ('github', 'GitHub', null, 2),
  ('linkedin', 'LinkedIn', null, 3),
  ('email', 'Portfolio email', 'mailto:example@email.com', 4)
) as v(platform, label, url, sort_order)
where not exists (select 1 from public.social_links);

-- testimonials: no starting rows

