// Generates supabase/seed.sql from the starting content in src/data.
// Usage: node scripts/build-seed.mjs
import { writeFileSync } from "node:fs";
import { profile } from "../src/data/profile.js";
import { skills } from "../src/data/skills.js";
import { projects } from "../src/data/projects.js";
import { services } from "../src/data/services.js";
import { education } from "../src/data/education.js";
import { experience } from "../src/data/experience.js";
import { certificates } from "../src/data/certificates.js";
import { resume } from "../src/data/resume.js";
import { socialLinks } from "../src/data/socialLinks.js";
import { tools } from "../src/data/tools.js";
import { testimonials } from "../src/data/testimonials.js";
import { PROJECT_STATUSES, SERVICE_AVAILABILITY, SKILL_LEVELS } from "../src/services/content.js";

const sql = (value) => {
  if (value === null || value === undefined || value === "") return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.length ? `array[${value.map(sql).join(", ")}]::text[]` : "'{}'::text[]";
  return `'${String(value).replace(/'/g, "''")}'`;
};
const json = (value) => `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
const pick = (value, allowed) => allowed.find((option) => option.toLowerCase() === String(value || "").toLowerCase()) || null;
const isoDate = (value) => (/^\d{4}-\d{2}-\d{2}$/.test(value || "") ? value : null);

function insert(table, rows) {
  if (!rows.length) return `-- ${table}: no starting rows\n`;
  const columns = Object.keys(rows[0]);
  const values = rows.map((row) => `  (${columns.map((column) => row[column]).join(", ")})`).join(",\n");
  return `insert into public.${table} (${columns.join(", ")})\nselect * from (values\n${values}\n) as v(${columns.join(", ")})\nwhere not exists (select 1 from public.${table});\n`;
}

const out = [];
out.push("-- ============================================================================");
out.push("-- LANZ.SYS portfolio — starting content (generated by scripts/build-seed.mjs)");
out.push("-- Run AFTER schema.sql. Each table is only filled if it is still empty,");
out.push("-- so running this again never duplicates or overwrites your edits.");
out.push("-- ============================================================================\n");

out.push(`insert into public.profile (id, name, roles, role, tagline, intro, about, image, image_alt, player_class, specialization, availability, location, email, career_goal)
values (1, ${[profile.name, profile.roles || [], profile.role, profile.tagline, profile.intro, profile.about, profile.image, profile.imageAlt, profile.playerClass, profile.specialization, profile.availability, profile.location, profile.email, profile.careerGoal].map(sql).join(", ")})
on conflict (id) do nothing;\n`);

out.push(`insert into public.resume (id, title, description, file, url, status)
values (1, ${[resume.title, resume.description, resume.file, resume.url, resume.status].map(sql).join(", ")})
on conflict (id) do nothing;\n`);

out.push(insert("skills", skills.map((item, index) => ({
  name: sql(item.name), category: sql(item.category), level: sql(pick(item.level, SKILL_LEVELS)), description: sql(item.description),
  related: sql(item.related || []), sort_order: index,
}))));

out.push(insert("services", services.map((item, index) => ({
  name: sql(item.name), category: sql(item.category), description: sql(item.description), capabilities: sql(item.capabilities || []),
  deliverables: sql(item.deliverables || []), tools: sql(item.tools || []), availability: sql(pick(item.availability, SERVICE_AVAILABILITY)),
  related_projects: sql(item.relatedProjects || []), cta: sql(item.cta), featured: false, sort_order: index,
}))));

out.push(insert("tools", tools.map((item, index) => ({
  name: sql(item.name), category: sql(item.category), usage: sql(item.usage), proficiency: sql(item.proficiency), sort_order: index,
}))));

out.push(insert("projects", projects.map((item, index) => ({
  name: sql(item.name), category: sql(item.category), status: sql(pick(item.status, PROJECT_STATUSES)), year: sql(item.year),
  description: sql(item.description), objective: sql(item.objective), challenge: sql(item.challenge), solution: sql(item.solution),
  role: sql(item.role), features: sql(item.features || []), results: sql(item.results || []), tech: sql(item.tech || []),
  cover_image: sql(item.media), video: sql(item.video), gallery: json(item.gallery || []),
  github_url: sql(item.githubUrl), live_url: sql(item.liveUrl), featured: Boolean(item.featured), sort_order: index,
}))));

for (const [table, rows] of [["experience", experience], ["education", education]]) {
  out.push(insert(table, rows.map((item, index) => ({
    title: sql(item.title), organization: sql(item.organization), period: sql(item.period), description: sql(item.description), sort_order: index,
  }))));
}

out.push(insert("certificates", certificates.map((item, index) => ({
  title: sql(item.title), issuer: sql(item.issuer), issued_on: `${sql(isoDate(item.date))}::date`, credential_id: sql(item.credentialId),
  credential_url: sql(item.credentialUrl), description: sql(item.description), image: sql(item.image), file: sql(item.pdf),
  related_skills: sql(item.relatedSkills || []), sort_order: index,
}))));

out.push(insert("social_links", socialLinks.map((item, index) => ({
  platform: sql(item.platform || "other"), label: sql(item.label), url: sql(item.placeholder ? null : item.href), sort_order: index,
}))));

out.push(insert("testimonials", testimonials.map((item, index) => ({
  name: sql(item.name), role: sql(item.role), message: sql(item.message), project: sql(item.project), sort_order: index,
}))));

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), `${out.join("\n")}\n`);
console.log("Wrote supabase/seed.sql");
